### ISSUE TITLE
Running clang-tidy-review outside of container

### ISSUE THREAD

**Issue by bwrsandman** [ZedThree/clang-tidy-review#122]
I wanted to post this in discussions but it's not enabled for the repo.

Here's how I am able to run the clang-tidy review script directly on the github runner environments without needing the ubuntu container.
Why would you do this?
1. Saves time spent each run fetching the docker and installing packages with `apt`
2. You can run this on any of the runners that github provides or that you host yourself.
3. You can use any version of clang-tidy that is available to you in this environment. Usually new llvm versions appear on the runners before they are enabled in this repo.

```yaml
name: Clang Tidy
on:
  pull_request_target:  # Required to post comments on PR from forks
jobs:
  clang-tidy-review:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    if: startsWith(github.event_name, 'pull_request')  # Posting a review only makes sense on PRs
    steps:
      # Repo config for pull_request_target
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: recursive
      - name: Add base repo to git config
        run: git remote add upstream ${{ github.event.pull_request.base.repo.html_url }}
        if: startsWith(github.event_name, 'pull_request')

      # My project uses vcpkg and cmake. I use that to generate the compilation database
      - uses: lukka/get-cmake@latest
      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Run CMake+vcpkg to build packages.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DCMAKE_EXPORT_COMPILE_COMMANDS=ON']"

      # Upload the compilation database for debugging
      - uses: actions/upload-artifact@v3
        with:
          name: CompilationDatabase-${{matrix.os}}
          path: cmake-build-presets/ninja-multi-vcpkg/compile_commands.json

      # If for some reason you want to run on mac
      - name: Install MacOS LLVM dependencies
        run: |
          brew install pkg-config
          mkdir -p ~/bin
          brew --prefix llvm@15
          ls $(brew --prefix llvm@15)/bin
          ln -s $(brew --prefix llvm@15)/bin/clang-tidy ~/bin/clang-tidy
          echo "export PATH=$PATH:~/bin" >> $GITHUB_ENV
          ls -l ~/bin/clang-tidy
          clang-tidy --version
        if: startsWith(matrix.os, 'macos')

      # Checkout the review source for the python package
      - name: Checkout clang-tidy-review
        uses: actions/checkout@v4
        with:
          repository: ZedThree/clang-tidy-review
          ref: master
          path: clang-tidy-review

      # Install the python package and run review
      - name: Non-docker clang-tidy-check
        run: |
          clang-tidy --version
          python3 -m pip install pip -U
          python3 -m pip install ${{github.workspace}}/clang-tidy-review/post/clang_tidy_review
          review --token=${{ secrets.GITHUB_TOKEN }} --repo=${{ github.event.pull_request.head.repo.full_name }} --pr=${{ github.event.pull_request.number }} --clang_tidy_binary=clang-tidy --build_dir=cmake-build-presets/ninja-multi-vcpkg --config_file=.clang-tidy --split_workflow=True
        env:
          USER: ${{ github.event.pull_request.user.login }}

     # Upload the review for the next job
      - uses: actions/upload-artifact@v3
        with:
          name: ClangTidyReviewOutputs-${{matrix.os}}
          path: |
            clang-tidy-review-metadata.json
            clang-tidy-review-output.json
            clang_tidy_review.yaml

  # Second part of the split job
  clang-tidy-comments:
    runs-on: ubuntu-latest
    needs: clang-tidy-review
    steps:
      - name: Checkout clang-tidy-review
        uses: actions/checkout@v4
        with:
          repository: ZedThree/clang-tidy-review
          ref: master
          path: clang-tidy-review

     # Download all the reviews
      - uses: actions/download-artifact@v3
        with:
          name: ClangTidyReviewOutputs-ubuntu-latest
          path: ubuntu-latest
      - uses: actions/download-artifact@v3
        with:
          name: ClangTidyReviewOutputs-macos-latest
          path: macos-latest
      - uses: actions/download-artifact@v3
        with:
          name: ClangTidyReviewOutputs-windows-latest
          path: windows-latest

      # Again install and run the python package to post the review
      - name: Non-docker clang-tidy-check
        run: |
          clang-tidy --version
          python3 -m pip install pip -U
          python3 -m pip install ${{github.workspace}}/clang-tidy-review/post/clang_tidy_review
          cp ubuntu-latest/clang-tidy-review-metadata.json .
          post --token=${{ secrets.GITHUB_TOKEN }} --repo=${{ github.event.pull_request.head.repo.full_name }} ubuntu-latest/clang-tidy-review-output.json macos-latest/clang-tidy-review-output.json windows-latest/clang-tidy-review-output.json

```
