### ISSUE TITLE
Exclude not working?

### ISSUE THREAD

**Issue by vadi2** [ZedThree/clang-tidy-review#19]
I've got my action setup like this:

```
- name: Check C++ changes against style guide
      uses: ZedThree/clang-tidy-review@v0.7.0
      id: static_analysis
      with:
        build_dir: 'b/ninja' # path is relative to checkout directory
        # PLACEMARKER: list of clang-tidy checks
        clang_tidy_checks: '-*,performance-*,readability-*,bugprone-*, ...'
        # the action doesn't see system-level libraries, need to replicate them here
        apt_packages: 'pkg-config,libzip-dev,libglu1-mesa-dev,libpulse-dev'
        exclude: '3rdparty'
```

but it does not seem like the exclude parameter is getting passed to the action...

![image](https://user-images.githubusercontent.com/110988/140636162-1e1b815d-74d7-4c3c-999a-386235ca9e70.png)

What could be going wrong here?
