### ISSUE TITLE
Can not find `mpi.h`

### ISSUE THREAD

**Issue by christian512** [ZedThree/clang-tidy-review#62]
I am trying to run this action on some C++ code which uses MPI. 

I am using the `build_commands.json` generated by `CMake` as an input to this Action, but I still get an error:

`'mpi.h' file not found [clang-diagnostic-error]`

Locally, I get this error when the `build_commands.json` is not given to `clang-tidy`. 
Do you have any idea, why `clang-tidy` can not find `mpi.h` in the current setup? 

This is what my action looks like:
(the `CMAKE_EXPORT_COMPILE_COMMANDS ON` is set in the `CMakeLists.txt`)

```
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'intelmpi'

      - name: Compile code
        run: |
          cmake .
          make

      - uses: ZedThree/clang-tidy-review@v0.10.0
        id: review
        with:
          config_file: .clang-tidy
          lgtm_comment_body: ""
          split_workflow: true

```

**Comment by Nerixyz** [comment]
There's a (seemingly) similar problem in chatterino:

```
clang-tidy failed with return code 1 and error:
81416 warnings and 2 errors generated.
Error while processing /github/workspace/src/providers/seventv/SeventvBadges.cpp.
Suppressed 81415 warnings (81413 in non-user code, 2 due to line filter).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).

Output was:
warning: optimization flag '-fno-fat-lto-objects' is not supported [clang-diagnostic-ignored-optimization-argument]
/github/workspace/src/common/Aliases.hpp:3:10: error: 'QHash' file not found [clang-diagnostic-error]
#include <QHash>
         ^~~~~~~

Took: 0:00:08.269470
```
There are other cases where clang-tidy returned with [`'boost/optional.hpp' file not found`](https://github.com/Chatterino/chatterino2/pull/4321#discussion_r1083314931) even though the build succeeded.

I think the root issue here is that this action runs in docker, and thus can't find files set-up before. In your case it's `mpi.h` and in chatterino's case it's Qt and boost.

**Comment by ZedThree** [comment]
Hi @christian512, very sorry for it's taken me a long time to reply! This action runs in a separate container to the rest of the workflow, which means it doesn't have access to the same packages. There's an `apt_packages` argument that you can use to pass in a list of packages to install inside the container. I guess you most likely want:

```yaml
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'intelmpi'

      - name: Compile code
        run: |
          cmake .
          make

      - uses: ZedThree/clang-tidy-review@v0.10.0
        id: review
        with:
          config_file: .clang-tidy
          lgtm_comment_body: ""
          split_workflow: true
          apt_packages: "python3-mpi4py"
```

Hope that helps!
